:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30

:queues:
  - [low_priority, 1]
  - [high_priority, 2] # high priority

:schedule:
  RewardWorker:
    cron: '0 8 * * *'  # At 08:00 AM Everyday
    queue: high_priority
    enabled: true